name: Maildrop E2E

on:
  push:
    branches:
      - main


jobs:
    runner:
        runs-on: ubuntu-latest

        steps:
        - name: Initialize node & npm
          uses: actions/checkout@v4

        # - name: Execute Cypress Test
        #   uses: cypress-io/github-action@v6 # Runs test in parallel using settings above
        #   env:
        #     CYPRESS_MAILOSAUR_API_KEY: ${{secrets.CYPRESS_MAILOSAUR_API_KEY}} 
        - name: BrowserStack Env Setup
          uses: 'browserstack/github-actions/setup-env@master'
          with:
            username:  ${{ secrets.BROWSERSTACK_USERNAME }}
            access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
            CYPRESS_MAILOSAUR_API_KEY: ${{secrets.CYPRESS_MAILOSAUR_API_KEY}} 
            run: npx browserstack-cypress run --sync


        - name: Upload Report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: reports
            path: |
              cypress/reports/  