name: Maildrop E2E

on:
  push:
    branches:
      - main


jobs:
    runner:
        runs-on: ubuntu-latest

        steps:
        - name: Initialize node & npm
          uses: actions/checkout@v4

        - name: Execute Cypress Test
          uses: cypress-io/github-action@v6 
          record: true
          parallel: true # Runs test in parallel using settings above
          env:
            CYPRESS_MAILOSAUR_API_KEY: ${{secrets.CYPRESS_MAILOSAUR_API_KEY}}  
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

        - name: Upload Report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: reports
            path: |
              cypress/reports/  